name: clean_architecture_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter_web_plugins:
    sdk: flutter
  get_it: ^7.2.0
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  http: ^0.13.4
  firebase_core: ^1.12.0
  shared_preferences: any
  cross_connectivity: ^3.0.3
  cupertino_icons: ^1.0.4
  url_strategy: ^0.2.0
  firebase_auth: ^3.3.7
  drift: ^1.4.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: any
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^1.4.0
  build_runner: ^2.1.7

flutter:
  uses-material-design: true
